# Generated by Django 3.1 on 2020-11-06 02:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201105_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
